[general]
groq_api_key = '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'
openai_api_key = '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'