[general]
groq_api_key = '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'
openai_api_key = 'sk-uNwqsEpCAa8AmOZxpuE13VYNQT2Uj0VO6GA-g345QPT3BlbkFJ7GJALiqF0zgnVKSiMi8KSdUBmnUqqe_1UQKiis3sUA'
